Config = {}

Config.Framework = 'ESX'

Config.Database = {
    table_prefix = 'gift_system_'
}

Config.Web = {
    port = 3000,
    admin_password = 'admin123'
}

Config.GiftTypes = {
    item = {
        enabled = true,
        label = '物品'
    },
    money = {
        enabled = true,
        label = '货币',
        types = {
            cash = { label = '现金', account = 'money' },
            bank = { label = '银行', account = 'bank' },
            black_money = { label = '黑钱', account = 'black_money' }
        }
    },
    weapon = {
        enabled = true,
        label = '武器'
    },
    vehicle = {
        enabled = true,
        label = '车辆'
    }
}

Config.RedPacket = {
    max_players = 100,
    timeout = 300,
    modes = {
        random = {
            label = '随机分配',
            description = '金额随机分配给抢到的玩家'
        },
        equal = {
            label = '平均分配',
            description = '金额平均分配给抢到的玩家'
        },
        first_come = {
            label = '先到先得',
            description = '前N个玩家抢到全额'
        }
    }
}

Config.Weapons = {
    'WEAPON_PISTOL',
    'WEAPON_COMBATPISTOL',
    'WEAPON_APPISTOL',
    'WEAPON_PISTOL50',
    'WEAPON_SNSPISTOL',
    'WEAPON_HEAVYPISTOL',
    'WEAPON_VINTAGEPISTOL',
    'WEAPON_MARKSMANPISTOL',
    'WEAPON_REVOLVER',
    'WEAPON_DOUBLEACTION',
    'WEAPON_MICROSMG',
    'WEAPON_SMG',
    'WEAPON_ASSAULTSMG',
    'WEAPON_COMBATPDW',
    'WEAPON_MACHINEPISTOL',
    'WEAPON_MINISMG',
    'WEAPON_PUMPSHOTGUN',
    'WEAPON_SAWNOFFSHOTGUN',
    'WEAPON_ASSAULTSHOTGUN',
    'WEAPON_BULLPUPSHOTGUN',
    'WEAPON_HEAVYSHOTGUN',
    'WEAPON_DBSHOTGUN',
    'WEAPON_AUTOSHOTGUN',
    'WEAPON_ASSAULTRIFLE',
    'WEAPON_CARBINERIFLE',
    'WEAPON_ADVANCEDRIFLE',
    'WEAPON_SPECIALCARBINE',
    'WEAPON_BULLPUPRIFLE',
    'WEAPON_COMPACTRIFLE',
    'WEAPON_MG',
    'WEAPON_COMBATMG',
    'WEAPON_GUSENBERG',
    'WEAPON_SNIPERRIFLE',
    'WEAPON_HEAVYSNIPER',
    'WEAPON_MARKSMANRIFLE',
    'WEAPON_GRENADELAUNCHER',
    'WEAPON_RPG',
    'WEAPON_STINGER',
    'WEAPON_MINIGUN',
    'WEAPON_GRENADE',
    'WEAPON_STICKYBOMB',
    'WEAPON_SMOKEGRENADE',
    'WEAPON_BZGAS',
    'WEAPON_MOLOTOV',
    'WEAPON_PETROLCAN',
    'WEAPON_FIREEXTINGUISHER',
    'WEAPON_BALL',
    'WEAPON_SNOWBALL',
    'WEAPON_BAT',
    'WEAPON_KNUCKLE',
    'WEAPON_KNIFE',
    'WEAPON_MACHETE',
    'WEAPON_SWITCHBLADE',
    'WEAPON_BOTTLE',
    'WEAPON_CROWBAR',
    'WEAPON_UNARMED',
    'WEAPON_FLASHLIGHT',
    'WEAPON_NIGHTSTICK',
    'WEAPON_HAMMER',
    'WEAPON_WRENCH',
    'WEAPON_GOLFCLUB',
    'WEAPON_BATTLEAXE',
    'WEAPON_POOLCUE',
    'WEAPON_PIPEWRENCH',
    'WEAPON_STONE_HATCHET'
}

Config.Vehicles = {
    'adder',
    'airsuper',
    'akuma',
    'alpha',
    'annie',
    'archer',
    'ardent',
    'armet',
    'asea',
    'asterope',
    'autarch',
    'banshee',
    'bestiagts',
    'bifta',
    'bison',
    'blade',
    'blista',
    'bmx',
    'boor',
    'boxville',
    'brioso',
    'btype',
    'buccaneer',
    'buffalo',
    'bullet',
    'burrito',
    'bus',
    'buzzard',
    'cablecar',
    'caddy',
    'carbonizzare',
    'casco',
    'cavalcade',
    'cheburek',
    'cheetah',
    'chino',
    'clique',
    'cognoscenti',
    'comet',
    'coquette',
    'cutter',
    'daemon',
    'deathbike',
    'deluxo',
    'deviant',
    'dilettante',
    'dinghy',
    'dloader',
    'dominator',
    'draft',
    'drafter',
    'dukes',
    'dune',
    'elegy',
    'entity',
    'escher',
    'everon',
    'faction',
    'faggio',
    'felon',
    'feltzer',
    'firetruck',
    'flashgt',
    'fmj',
    'forklift',
    'frogger',
    'futo',
    'gauntlet',
    'gb200',
    'glendale',
    'gp1',
    'grafter',
    'granger',
    'gt500',
    'hakuchou',
    'halberd',
    'handler',
    'hexer',
    'hotknife',
    'huntley',
    'hustler',
    'infernus',
    'ingot',
    'issi',
    'italigtb',
    'jackal',
    'jb700',
    'jester',
    'journey',
    'kalahari',
    'kamacho',
    'karin',
    'khanjali',
    'khamsin',
    'komoda',
    'kuruma',
    'landstalker',
    'le7b',
    'leone',
    'lerata',
    'locust',
    'lurcher',
    'luxury',
    'lynx',
    'mamba',
    'massacro',
    'maverick',
    'mesa',
    'militia',
    'minivan',
    'monroe',
    'monster',
    'mule',
    'nebula',
    'neon',
    'nimbus',
    'ninef',
    'omnisegt',
    'oppressor',
    'oracle',
    'osiris',
    'packer',
    'panto',
    'paradise',
    'pariah',
    'patriot',
    'pbus',
    'penumbra',
    'phoenix',
    'picador',
    'pigalle',
    'pounder',
    'premier',
    'primo',
    'prototipo',
    'radi',
    'raiden',
    'rapidgt',
    'reaper',
    'rebel',
    'regina',
    'revolter',
    'rhapsody',
    'riata',
    'riot',
    'rocoto',
    'ruiner',
    'rumpo',
    'sadler',
    'sanchez',
    'sentinel',
    'serrano',
    'seven70',
    'sheava',
    'sultan',
    'suntrap',
    'surano',
    'surfer',
    'sultanrs',
    'superd',
    'taipan',
    'tampa',
    'toro',
    'torero',
    'toros',
    'tourus',
    'towtruck',
    'tropos',
    'tulip',
    'turismor',
    'tyrus',
    'vacca',
    'vagner',
    'vindicator',
    'virgo',
    'voltic',
    'windsor',
    'warrener',
    'washington',
    'z190',
    'zentorno'
}
